export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'

// GITHUB API
export const GITHUB_SET_USERNAME = 'GITHUB_SET_USERNAME'
export const GITHUB_SET_PASSWORD = 'GITHUB_SET_PASSWORD'
export const GITHUB_SET_OWNER = 'GITHUB_SET_OWNER'
export const GITHUB_SET_REPO = 'GITHUB_SET_REPO'
export const GITHUB_GET_ISSUE = 'GITHUB_GET_ISSUE'
