export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'

// GITHUB API
export const GITHUB_SET_USERNAME = 'GITHUB_SET_USERNAME'
export const GITHUB_SET_PASSWORD = 'GITHUB_SET_PASSWORD'
export const GITHUB_SET_OWNER = 'GITHUB_SET_OWNER'
export const GITHUB_SET_REPO = 'GITHUB_SET_REPO'
export const GITHUB_GET_ISSUE = 'GITHUB_GET_ISSUE'
export const GITHUB_SET_ISSUE = 'GITHUB_SET_ISSUE'
export const GITHUB_GET_PULL = 'GITHUB_GET_PULL'
export const GITHUB_SET_PULL = 'GITHUB_SET_PULL'

// USER SETTINGS
export const USER_SETTINGS_SAVE = 'USER_SETTINGS_SAVE'
export const USER_SETTINGS_LOAD = 'USER_SETTINGS_LOAD'

// LOCAL GIT
export const GIT_DETECT_BRANCH_NAME = 'GIT_GET_BRANCH_NAME'
export const GIT_SET_BRANCH_NAME = 'GIT_GET_BRANCH_NAME'
